# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servos_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='servos_msg.proto',
  package='servos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10servos_msg.proto\x12\x06servos\"/\n\rMotorPosition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x01\"B\n\x10\x41\x63tuatorRequests\x12.\n\x0fmotor_positions\x18\x01 \x03(\x0b\x32\x15.servos.MotorPositionb\x06proto3'
)




_MOTORPOSITION = _descriptor.Descriptor(
  name='MotorPosition',
  full_name='servos.MotorPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='servos.MotorPosition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='servos.MotorPosition.position', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=75,
)


_ACTUATORREQUESTS = _descriptor.Descriptor(
  name='ActuatorRequests',
  full_name='servos.ActuatorRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_positions', full_name='servos.ActuatorRequests.motor_positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=143,
)

_ACTUATORREQUESTS.fields_by_name['motor_positions'].message_type = _MOTORPOSITION
DESCRIPTOR.message_types_by_name['MotorPosition'] = _MOTORPOSITION
DESCRIPTOR.message_types_by_name['ActuatorRequests'] = _ACTUATORREQUESTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotorPosition = _reflection.GeneratedProtocolMessageType('MotorPosition', (_message.Message,), {
  'DESCRIPTOR' : _MOTORPOSITION,
  '__module__' : 'servos_msg_pb2'
  # @@protoc_insertion_point(class_scope:servos.MotorPosition)
  })
_sym_db.RegisterMessage(MotorPosition)

ActuatorRequests = _reflection.GeneratedProtocolMessageType('ActuatorRequests', (_message.Message,), {
  'DESCRIPTOR' : _ACTUATORREQUESTS,
  '__module__' : 'servos_msg_pb2'
  # @@protoc_insertion_point(class_scope:servos.ActuatorRequests)
  })
_sym_db.RegisterMessage(ActuatorRequests)


# @@protoc_insertion_point(module_scope)
