# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servos_msg2_pb2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='servos_msg2_pb2.proto',
  package='servos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15servos_msg2_pb2.proto\x12\x06servos\"/\n\rMotorPosition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x01\"B\n\x10\x41\x63tuatorRequests\x12.\n\x0fmotor_positions\x18\x01 \x03(\x0b\x32\x15.servos.MotorPosition\"H\n\x0eImuMeasurement\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04roll\x18\x02 \x01(\x01\x12\r\n\x05pitch\x18\x03 \x01(\x01\x12\x0b\n\x03yaw\x18\x04 \x01(\x01\"E\n\x12SensorMeasurements\x12/\n\x0fimu_measurement\x18\x01 \x03(\x0b\x32\x16.servos.ImuMeasurement\" \n\x08Position\x12\t\n\x01X\x18\x01 \x01(\x01\x12\t\n\x01Y\x18\x02 \x01(\x01\"b\n\rRobotPosition\x12(\n\x0erobot_position\x18\x01 \x03(\x0b\x32\x10.servos.Position\x12\'\n\rball_position\x18\x02 \x03(\x0b\x32\x10.servos.Positionb\x06proto3'
)




_MOTORPOSITION = _descriptor.Descriptor(
  name='MotorPosition',
  full_name='servos.MotorPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='servos.MotorPosition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='servos.MotorPosition.position', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=80,
)


_ACTUATORREQUESTS = _descriptor.Descriptor(
  name='ActuatorRequests',
  full_name='servos.ActuatorRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_positions', full_name='servos.ActuatorRequests.motor_positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=148,
)


_IMUMEASUREMENT = _descriptor.Descriptor(
  name='ImuMeasurement',
  full_name='servos.ImuMeasurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='servos.ImuMeasurement.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roll', full_name='servos.ImuMeasurement.roll', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='servos.ImuMeasurement.pitch', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='servos.ImuMeasurement.yaw', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=222,
)


_SENSORMEASUREMENTS = _descriptor.Descriptor(
  name='SensorMeasurements',
  full_name='servos.SensorMeasurements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imu_measurement', full_name='servos.SensorMeasurements.imu_measurement', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=293,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='servos.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='servos.Position.X', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Y', full_name='servos.Position.Y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=327,
)


_ROBOTPOSITION = _descriptor.Descriptor(
  name='RobotPosition',
  full_name='servos.RobotPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_position', full_name='servos.RobotPosition.robot_position', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball_position', full_name='servos.RobotPosition.ball_position', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=427,
)

_ACTUATORREQUESTS.fields_by_name['motor_positions'].message_type = _MOTORPOSITION
_SENSORMEASUREMENTS.fields_by_name['imu_measurement'].message_type = _IMUMEASUREMENT
_ROBOTPOSITION.fields_by_name['robot_position'].message_type = _POSITION
_ROBOTPOSITION.fields_by_name['ball_position'].message_type = _POSITION
DESCRIPTOR.message_types_by_name['MotorPosition'] = _MOTORPOSITION
DESCRIPTOR.message_types_by_name['ActuatorRequests'] = _ACTUATORREQUESTS
DESCRIPTOR.message_types_by_name['ImuMeasurement'] = _IMUMEASUREMENT
DESCRIPTOR.message_types_by_name['SensorMeasurements'] = _SENSORMEASUREMENTS
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['RobotPosition'] = _ROBOTPOSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotorPosition = _reflection.GeneratedProtocolMessageType('MotorPosition', (_message.Message,), {
  'DESCRIPTOR' : _MOTORPOSITION,
  '__module__' : 'servos_msg2_pb2_pb2'
  # @@protoc_insertion_point(class_scope:servos.MotorPosition)
  })
_sym_db.RegisterMessage(MotorPosition)

ActuatorRequests = _reflection.GeneratedProtocolMessageType('ActuatorRequests', (_message.Message,), {
  'DESCRIPTOR' : _ACTUATORREQUESTS,
  '__module__' : 'servos_msg2_pb2_pb2'
  # @@protoc_insertion_point(class_scope:servos.ActuatorRequests)
  })
_sym_db.RegisterMessage(ActuatorRequests)

ImuMeasurement = _reflection.GeneratedProtocolMessageType('ImuMeasurement', (_message.Message,), {
  'DESCRIPTOR' : _IMUMEASUREMENT,
  '__module__' : 'servos_msg2_pb2_pb2'
  # @@protoc_insertion_point(class_scope:servos.ImuMeasurement)
  })
_sym_db.RegisterMessage(ImuMeasurement)

SensorMeasurements = _reflection.GeneratedProtocolMessageType('SensorMeasurements', (_message.Message,), {
  'DESCRIPTOR' : _SENSORMEASUREMENTS,
  '__module__' : 'servos_msg2_pb2_pb2'
  # @@protoc_insertion_point(class_scope:servos.SensorMeasurements)
  })
_sym_db.RegisterMessage(SensorMeasurements)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'servos_msg2_pb2_pb2'
  # @@protoc_insertion_point(class_scope:servos.Position)
  })
_sym_db.RegisterMessage(Position)

RobotPosition = _reflection.GeneratedProtocolMessageType('RobotPosition', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTPOSITION,
  '__module__' : 'servos_msg2_pb2_pb2'
  # @@protoc_insertion_point(class_scope:servos.RobotPosition)
  })
_sym_db.RegisterMessage(RobotPosition)


# @@protoc_insertion_point(module_scope)
